name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notifications
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ğŸ“¦ **GitHub ã«æ›´æ–°ãŒã‚ã‚Šã¾ã—ãŸ**
            ãƒªãƒã‚¸ãƒˆãƒª: ${{ github.repository }}
            å®Ÿè¡Œè€…: ${{ github.actor }}
            ãƒ–ãƒ©ãƒ³ãƒ: ${{ github.ref_name }}
            å†…å®¹: ${{ github.event.head_commit.message }}
